from pathlib import Path

from docx import Document

from pmo_studio.cli import main


def test_docx_professional_sections_and_pdf_ready_html(tmp_path):
    source = tmp_path / "crm.md"
    source.write_text("""
# CRM
| STT | CHỨC NĂNG | MÔ TẢ |
| 1 | Quản lý Lead | Capture, qualify, assign lead |
| 2 | Opportunity Pipeline | Stage, forecast, approval workflow |
""", encoding="utf-8")
    main(["--root", str(tmp_path), "run-project", "crm-v14", "--source", str(source), "--customer", "Demo", "--product", "CRM", "--llm", "noop", "--profile", "customer"])
    docx = tmp_path / "crm-v14/exports/customer/pmo-documentation-pack.docx"
    pdf_html = tmp_path / "crm-v14/exports/customer/pmo-dashboard-print-ready.html"
    assert docx.exists()
    assert pdf_html.exists()
    doc = Document(docx)
    text = "\n".join(p.text for p in doc.paragraphs)
    assert "Document Control" in text
    assert "Approval / Sign-off" in text
    assert "Change History" in text
    assert "Generated by PMO Studio" in doc.sections[0].footer.paragraphs[0].text
    assert "@media print" in pdf_html.read_text(encoding="utf-8")
