"""PMO Studio CLI."""
from __future__ import annotations

import argparse
from pathlib import Path

from pmo_studio.core.project import Project, DEFAULT_ROOT
from pmo_studio.generators.stage0 import generate_stage0
from pmo_studio.generators.ba import generate_ba
from pmo_studio.generators.source_ba import generate_ba_from_sources
from pmo_studio.generators.po_pm_ic import generate_po, generate_pm, generate_ic
from pmo_studio.gates.gate_a import run_gate_a, save_gate_result as save_gate_a_result
from pmo_studio.gates.gate_bc import run_gate_b_or_c, save_gate_result as save_gate_bc_result
from pmo_studio.traceability.engine import TraceabilityEngine
from pmo_studio.traceability.validator import validate_traceability
from pmo_studio.exporters.static_html import export_static
from pmo_studio.exporters.docx_export import export_docx
from pmo_studio.exporters.bundle import export_bundle
from pmo_studio.exporters.pdf_export import export_pdf, export_pdf_ready_html
from pmo_studio.core.manifest import create_baseline, diff_against_baseline
from pmo_studio.core.change_request import create_change_request
from pmo_studio.eval.runner import run_eval, run_benchmark, V12_SAMPLE_CASES
from pmo_studio.llm.factory import build_llm
from pmo_studio.llm.reviewer import JSONLLMReviewer, build_gate_reviewer
from pmo_studio.rubrics.loader import ensure_default_rubrics
from pmo_studio.templates.loader import ensure_default_templates
from pmo_studio.gates.runner import run_all_gates
from pmo_studio.core.doctor import run_doctor
from pmo_studio.generators.refinement import refine_markdown_artifact
from pmo_studio.metrics.recorder import MetricsRecorder
from pmo_studio.core.registry import list_projects, recent_project, refresh_registry
from pmo_studio.core.lifecycle import summarize_project, summary_markdown, sync_lifecycle, archive_project, clone_project, set_lifecycle
from pmo_studio.llm.provider import api_key_status
from pmo_studio.domain.detector import detect_domain, write_domain_detection
from pmo_studio.core.dashboard import generate_project_index, generate_review_checklist
from pmo_studio.core.signoff import update_signoff, load_signoff
from pmo_studio.generators.source_ba import read_redacted_sources
from pmo_studio.core.artifact_manifest import write_artifact_manifest
from pmo_studio.templates.governance import list_versioned_templates, validate_templates
from pmo_studio.domain.manager import list_domains, inspect_domain, validate_domain, scaffold_domain, benchmark_domain, update_domain, export_domain, import_domain
from pmo_studio.integrations.telegram_workflow import build_delivery_manifest, ingest_inbound, run_session, load_session

DEFAULT_LLM_PROVIDER = "auto"
DEFAULT_LLM_MODEL = "Tier2"
DEFAULT_MAX_REFINE = 2
DEFAULT_GATE_TIMEOUT = 120
DEMO_ASSET_SOURCE = """# Asset Management Source Brief

Khách hàng cần hệ thống Quản lý trang thiết bị, tài sản nội bộ.

## Goals
- Số hóa danh mục tài sản/TTB: mã tài sản, tên, nhóm, serial, phòng ban, người sử dụng, ngày mua, nguyên giá, tình trạng.
- Quản lý cấp phát, bàn giao, thu hồi, điều chuyển tài sản theo nhân viên/phòng ban.
- Ghi nhận kiểm kê, bảo trì/sửa chữa, bảo hành, thanh lý và lịch sử biến động.
- Có báo cáo/dashboard theo phòng ban, người dùng, nhóm tài sản, trạng thái, kỳ kiểm kê.
- Có phân quyền Admin, Asset Manager, Department Manager, Staff, Auditor.

## MVP Scope
- Asset master and classification.
- Allocation, handover, return, transfer.
- Inventory, maintenance, liquidation request.
- Report/export.
- Permission, audit log, import/export validation.

## Phase 2 / Optional
- RFID full integration after device/vendor PoC.
- Realtime HRM/ERP/accounting API after API contract.
- Legal digital signature after provider/license confirmation.
- Advanced configurable workflow/rule engine if approval rules become complex.

## Acceptance Hints
- asset_code is generated by the system; user enters serial/external reference.
- Invalid import rows should be rejected with row-level errors while valid rows continue.
- Unauthorized UI/API action must return access denied/403 and write a security audit event.
- Report export must include asset_code, name, group, holder, department, status, original_cost and date columns.
"""


def _resolve_llm_provider(provider: str | None) -> str:
    """Resolve CLI default to the best available provider without breaking offline runs."""
    provider = provider or DEFAULT_LLM_PROVIDER
    if provider != "auto":
        return provider
    return "9router" if api_key_status().get("9router", "").startswith("set") else "noop"


def _resolve_slug(args) -> str:
    if getattr(args, 'slug', None):
        return args.slug
    recent = recent_project(Path(args.root))
    if not recent:
        raise SystemExit('No PMO project found. Use init first or pass <slug>.')
    return recent.slug


def cmd_init(args):
    p = Project.create(args.slug, customer=args.customer, root_base=Path(args.root), domain_pack=args.domain_pack)
    sources = [Path(s) for s in args.source]
    generate_stage0(p, brief=args.brief, products=args.product, sources=sources)
    print(f"Created project: {p.root}")


def cmd_generate(args):
    args.slug = _resolve_slug(args)
    p = Project.load(args.slug, root_base=Path(args.root))
    recorder = MetricsRecorder(p.root)
    llm_provider = _resolve_llm_provider(args.llm)
    model = args.model or DEFAULT_LLM_MODEL
    llm = build_llm(llm_provider, model)
    with recorder.span("generate", persona=args.persona, from_sources=args.from_sources, llm=llm_provider, model=model):
        if args.persona in {"po", "all"}: generate_po(p)
        if args.persona in {"pm", "all"}: generate_pm(p)
        if args.persona in {"ba", "all"}:
            generate_ba_from_sources(p, llm=llm) if args.from_sources else generate_ba(p)
        if args.persona in {"ic", "all"}: generate_ic(p)
    if args.refine:
        targets = _refine_targets(p, args.persona)
        for stage, artifact in targets:
            if artifact.exists() and artifact.suffix.lower() == ".md":
                print(f"Refining {stage}: {artifact.relative_to(p.root)}", flush=True)
                with recorder.span("refine", stage=stage, artifact=str(artifact.relative_to(p.root))):
                    try:
                        rr = refine_markdown_artifact(artifact, stage, llm=llm, max_attempts=args.max_refine, model=model, domain_pack=p.config.domain_pack)
                    except Exception as exc:
                        rr = None
                        recorder.record("refine.error", stage=stage, artifact=str(artifact.relative_to(p.root)), error=type(exc).__name__, message=str(exc))
                        print(f"Refine skipped {stage}: {type(exc).__name__}: {exc}", flush=True)
                    if rr is not None:
                        recorder.record("refine.result", **rr.__dict__)
                        print(f"Refined {stage}: attempts={rr.attempts} gate_a={rr.gate_a_passed} gate_b={rr.gate_b_passed} changed={rr.changed}", flush=True)
    with recorder.span("trace.write"):
        TraceabilityEngine(p.root).write_outputs()
    metrics_path = recorder.save()
    print(f"Generated {args.persona} artifacts for {p.config.project_slug}")
    print(f"Metrics: {metrics_path}")


def _refine_targets(p: Project, persona: str):
    all_targets = []
    if persona in {"po", "all"}:
        all_targets.append(("po.vision", p.root / "artifacts" / "po" / "01-vision.md"))
    if persona in {"pm", "all"}:
        all_targets.append(("pm.charter", p.root / "artifacts" / "pm" / "01-charter.md"))
    if persona in {"ba", "all"}:
        all_targets.extend([
            ("ba.prd", p.root / "artifacts" / "ba" / "01-prd.md"),
            ("ba.brd", p.root / "artifacts" / "ba" / "02-brd.md"),
            ("ba.srs", p.root / "artifacts" / "ba" / "03-srs" / "srs.md"),
            ("ba.test_cases", p.root / "artifacts" / "ba" / "05-test-cases.md"),
        ])
    if persona in {"ic", "all"}:
        all_targets.extend([
            ("ic.deployment_plan", p.root / "artifacts" / "ic" / "03-deployment-plan.md"),
            ("ic.uat_plan", p.root / "artifacts" / "ic" / "04-uat-plan.md"),
        ])
    return all_targets


def cmd_gate(args):
    args.slug = _resolve_slug(args)
    p = Project.load(args.slug, root_base=Path(args.root))
    if args.layer == "A":
        result = run_gate_a(Path(args.artifact), args.stage)
        out = save_gate_a_result(result, p.root)
    else:
        llm_provider = _resolve_llm_provider(args.llm)
        model = args.model or DEFAULT_LLM_MODEL
        reviewer = JSONLLMReviewer(build_llm(llm_provider, model), model=model, fallback_on_error=True) if llm_provider != "noop" else None
        result = run_gate_b_or_c(Path(args.artifact), args.stage, args.layer, reviewer=reviewer)
        out = save_gate_bc_result(result, p.root)
    print(f"Gate {args.layer} {args.stage}: {'PASS' if result.passed else 'FAIL'} -> {out}")
    for c in result.checks:
        print(f"- [{'x' if c.passed else ' '}] {c.id}: {c.evidence}")


def cmd_trace(args):
    args.slug = _resolve_slug(args)
    p = Project.load(args.slug, root_base=Path(args.root))
    TraceabilityEngine(p.root).write_outputs()
    if args.validate:
        result = validate_traceability(p.root)
        print(f"Traceability validation: {'PASS' if result.passed else 'WARN'} nodes={result.node_count} edges={result.edge_count} missing={len(result.missing_upstream)} orphan={len(result.orphan_ids)}")
    print(f"Traceability written: {p.root / 'traceability'}")


def cmd_export(args):
    args.slug = _resolve_slug(args)
    p = Project.load(args.slug, root_base=Path(args.root))
    outputs = []
    if args.format in {"html", "all"}:
        outputs.append(export_static(p.root, force=args.force))
    if args.format in {"docx", "all"}:
        outputs.append(export_docx(p.root, profile=args.profile, force=args.force))
    if args.format in {"zip", "all"}:
        outputs.append(export_bundle(p.root, profile=args.profile, include_sources=args.include_redacted_sources, force=args.force))
    if args.format in {"pdf", "all"}:
        outputs.append(export_pdf(p.root, profile=args.profile, force=args.force))
    if args.format in {"pdf-html", "all"}:
        outputs.append(export_pdf_ready_html(p.root, profile=args.profile, force=args.force))
    for path in outputs:
        print(f"Exported: {path}")


def cmd_baseline(args):
    args.slug = _resolve_slug(args)
    p = Project.load(args.slug, root_base=Path(args.root))
    manifest = create_baseline(p.root, p.config.project_slug, args.version)
    p.state.lifecycle_state = "BASELINED"
    p.save()
    print(f"Baseline {args.version}: {manifest.item_count} files, sha256={manifest.manifest_sha256}")


def cmd_diff(args):
    args.slug = _resolve_slug(args)
    p = Project.load(args.slug, root_base=Path(args.root))
    diff = diff_against_baseline(p.root, args.version)
    print(f"Baseline diff {args.version}")
    for key in ["added", "modified", "removed"]:
        print(f"{key}: {len(diff[key])}")
        for item in diff[key][:30]:
            print(f"- {item}")
    print(f"unchanged_count: {diff['unchanged_count']}")


def cmd_cr(args):
    args.slug = _resolve_slug(args)
    p = Project.load(args.slug, root_base=Path(args.root))
    out = create_change_request(p, args.baseline, args.title, args.description, args.requested_by)
    print(f"Created CR: {out}")


def cmd_scaffold(args):
    ensure_default_rubrics()
    ensure_default_templates()
    print("Scaffolded default rubrics/templates")


def cmd_run_gates(args):
    args.slug = _resolve_slug(args)
    p = Project.load(args.slug, root_base=Path(args.root))
    llm_provider = _resolve_llm_provider(args.llm)
    reviewer = build_gate_reviewer(
        llm_provider,
        args.model or DEFAULT_LLM_MODEL,
        cache_root=args.gate_cache,
        fallback_on_error=args.gate_fallback,
        timeout=args.gate_timeout,
    ) if llm_provider != "noop" else None
    summary = run_all_gates(p, include_c=args.include_c, reviewer=reviewer)
    if reviewer:
        print(f"Reviewer: {llm_provider}/{args.model or DEFAULT_LLM_MODEL} cache={reviewer.cache.root if reviewer.cache else 'off'} timeout={args.gate_timeout}s")
    print(f"Quality summary: total={summary['total']} passed={summary['passed']} failed={summary['failed']} skipped={summary['skipped']}")
    print(f"Written: {p.root / 'quality' / 'summary.json'}")


def cmd_doctor(args):
    project = None
    if args.slug:
        project = Project.load(args.slug, root_base=Path(args.root))
    result = run_doctor(project)
    print(f"Doctor: {'PASS' if result['passed'] else 'WARN'}")
    for c in result['checks']:
        mark = 'x' if c['passed'] else ' '
        print(f"- [{mark}] {c['id']}: {c['evidence']}")


def cmd_list(args):
    if args.refresh:
        refresh_registry(Path(args.root))
    entries = list_projects(Path(args.root), include_archived=args.include_archived)
    if not entries:
        print('No PMO projects found')
        return
    for e in entries[:args.limit]:
        print(f"{e.slug}\t{e.customer}\t{e.lifecycle_state}\t{e.current_stage}\t{e.root}")


def cmd_recent(args):
    e = recent_project(Path(args.root))
    if not e:
        print('No PMO projects found')
        return
    print(f"{e.slug}\t{e.customer}\t{e.lifecycle_state}\t{e.current_stage}\t{e.root}")


def cmd_summary(args):
    args.slug = _resolve_slug(args)
    p = Project.load(args.slug, root_base=Path(args.root))
    print(summary_markdown(summarize_project(p)))


def cmd_sync_lifecycle(args):
    args.slug = _resolve_slug(args)
    p = Project.load(args.slug, root_base=Path(args.root))
    state = sync_lifecycle(p)
    print(f"Lifecycle {p.config.project_slug}: {state}")


def cmd_set_lifecycle(args):
    args.slug = _resolve_slug(args)
    p = Project.load(args.slug, root_base=Path(args.root))
    set_lifecycle(p, args.state)
    print(f"Lifecycle {p.config.project_slug}: {p.state.lifecycle_state}")


def cmd_archive(args):
    args.slug = _resolve_slug(args)
    if not args.yes:
        raise SystemExit("Archive requires --yes")
    p = Project.load(args.slug, root_base=Path(args.root))
    dest = archive_project(p, reason=args.reason, move=args.move)
    print(f"Archived {args.slug}: {dest}")


def cmd_clone(args):
    source_slug = _resolve_slug(args)
    source = Project.load(source_slug, root_base=Path(args.root))
    cloned = clone_project(source, args.new_slug, customer=args.customer)
    print(f"Cloned {source_slug} -> {cloned.config.project_slug}: {cloned.root}")


def cmd_demo(args):
    if args.name != "asset-management":
        raise SystemExit("Only demo available: asset-management")
    root = Path(args.root)
    slug = args.slug
    source_path = root / "_demo_sources" / "asset-management-source.md"
    source_path.parent.mkdir(parents=True, exist_ok=True)
    source_path.write_text(DEMO_ASSET_SOURCE, encoding="utf-8")
    project_root = root / slug
    if project_root.exists() and not args.force:
        raise SystemExit(f"Demo project already exists: {project_root}. Use --force to overwrite.")
    if project_root.exists():
        import shutil
        shutil.rmtree(project_root)
    print(f"Demo source: {source_path}")
    p = Project.create(slug, customer=args.customer, root_base=root, domain_pack="bteco")
    generate_stage0(
        p,
        brief="Generate a client-ready PMO documentation pack for an Asset Management MVP.",
        products=["Asset Management Demo"],
        sources=[source_path],
    )
    print(f"Created project: {p.root}")
    gen_args = argparse.Namespace(
        root=str(root), slug=slug, persona="all", from_sources=True,
        llm=args.llm, model=args.model, refine=False, max_refine=0,
    )
    cmd_generate(gen_args)
    cmd_trace(argparse.Namespace(root=str(root), slug=slug, validate=True))
    cmd_run_gates(argparse.Namespace(
        root=str(root), slug=slug, include_c=True, llm=args.llm, model=args.model,
        gate_cache=None, gate_timeout=DEFAULT_GATE_TIMEOUT, gate_fallback=True,
    ))
    cmd_export(argparse.Namespace(root=str(root), slug=slug, format="all", profile="customer", include_redacted_sources=False))
    cmd_summary(argparse.Namespace(root=str(root), slug=slug))


def cmd_signoff(args):
    args.slug = _resolve_slug(args)
    p = Project.load(args.slug, root_base=Path(args.root))
    path = update_signoff(p, args.role, args.status, approved_by=args.by, note=args.note)
    data = load_signoff(p)
    print(f"Signoff updated: {path}")
    print(f"Locked: {data.get('locked', False)}")


def cmd_index(args):
    args.slug = _resolve_slug(args)
    p = Project.load(args.slug, root_base=Path(args.root))
    checklist = generate_review_checklist(p)
    md, html = generate_project_index(p)
    print(f"Project index: {md}")
    print(f"HTML index: {html}")
    print(f"Review checklist: {checklist}")


def cmd_detect_domain(args):
    args.slug = _resolve_slug(args)
    p = Project.load(args.slug, root_base=Path(args.root))
    result = detect_domain(read_redacted_sources(p), project_slug=p.config.project_slug, customer=p.config.customer)
    out = write_domain_detection(p.root, result)
    print(f"Domain: {result.selected_domain} score={result.score:.3f} confidence={result.confidence}")
    print(f"Explanation: {result.explanation}")
    print(f"Written: {out}")

def cmd_manifest(args):
    args.slug = _resolve_slug(args)
    p = Project.load(args.slug, root_base=Path(args.root))
    out = write_artifact_manifest(p.root)
    print(f"Artifact manifest: {out}")

def cmd_templates(args):
    if args.action == "list":
        for row in list_versioned_templates():
            print(f"{row['id']}	{row['version']}	{row['path']}	{row['size_bytes']} bytes")
    else:
        result = validate_templates()
        print(f"Templates: {'PASS' if result['passed'] else 'FAIL'} version={result['version']}")
        for check in result['checks']:
            print(f"- [{'x' if check['passed'] else ' '}] {check['path']}")
        if not result['passed']:
            raise SystemExit(1)

def cmd_run_project(args):
    root = Path(args.root)
    project_root = root / args.slug
    if project_root.exists() and not args.force:
        raise SystemExit(f"Project already exists: {project_root}. Use --force to overwrite.")
    if project_root.exists() and args.force:
        import shutil; shutil.rmtree(project_root)
    p = Project.create(args.slug, customer=args.customer, root_base=root, domain_pack=args.domain_pack)
    generate_stage0(p, brief=args.brief, products=[args.product], sources=[Path(args.source)])
    cmd_detect_domain(argparse.Namespace(root=str(root), slug=args.slug))
    cmd_generate(argparse.Namespace(root=str(root), slug=args.slug, persona='all', from_sources=True, llm=args.llm, model=args.model, refine=args.refine, max_refine=args.max_refine))
    cmd_trace(argparse.Namespace(root=str(root), slug=args.slug, validate=True))
    cmd_run_gates(argparse.Namespace(root=str(root), slug=args.slug, include_c=True, llm=args.llm, model=args.model, gate_cache=None, gate_timeout=DEFAULT_GATE_TIMEOUT, gate_fallback=True))
    cmd_export(argparse.Namespace(root=str(root), slug=args.slug, format='all', profile=args.profile, include_redacted_sources=False, force=False))
    cmd_index(argparse.Namespace(root=str(root), slug=args.slug))
    cmd_manifest(argparse.Namespace(root=str(root), slug=args.slug))
    if args.signoff_final:
        cmd_signoff(argparse.Namespace(root=str(root), slug=args.slug, role='Final', status='approved', by=args.by, note='run-project final signoff'))
    cmd_summary(argparse.Namespace(root=str(root), slug=args.slug))


def cmd_web(args):
    from pmo_studio.webapp import run_web
    run_web(Path(args.root), host=args.host, port=args.port)

def cmd_telegram(args):
    if args.action == "ingest":
        result = ingest_inbound(Path(args.root), args.chat_id, message_id=args.message_id, source_path=args.source, text=args.text, slug=args.slug, customer=args.customer, product=args.product)
        print(result['prompt'])
        print(f"State: {result['state']}")
        print(f"Session: {result['session_path']}")
    elif args.action == "run-session":
        out = run_session(Path(args.root), args.chat_id, llm=args.llm, force=args.force)
        print(f"Telegram delivery manifest: {out}")
    elif args.action == "session":
        import json
        print(json.dumps(load_session(Path(args.root), args.chat_id).__dict__, ensure_ascii=False, indent=2))
    elif args.action == "prepare":
        run_args = argparse.Namespace(
            root=args.root, slug=args.slug, source=args.source, customer=args.customer, product=args.product,
            brief=args.brief, domain_pack=args.domain_pack, profile="customer", llm=args.llm, model=args.model,
            refine=False, max_refine=0, signoff_final=False, by=args.by, force=args.force,
        )
        cmd_run_project(run_args)
        p = Project.load(args.slug, root_base=Path(args.root))
        out = build_delivery_manifest(p.root, chat_id=args.chat_id)
        print(f"Telegram delivery manifest: {out}")
        data = __import__('json').loads(out.read_text(encoding='utf-8'))
        for f in data.get('files', []):
            print(f"- {f['label']}: {f['path']} ({f['size_bytes']} bytes)")
    elif args.action == "manifest":
        p = Project.load(args.slug, root_base=Path(args.root))
        out = build_delivery_manifest(p.root, chat_id=args.chat_id)
        print(f"Telegram delivery manifest: {out}")

def cmd_domains(args):
    if args.action == "list":
        for row in list_domains():
            print(f"{row['id']}	version={row['pack_version']}	keywords={row['keywords']}	modules={row['modules']}	{row['label']}")
    elif args.action == "inspect":
        import json
        print(json.dumps(inspect_domain(args.domain_id), ensure_ascii=False, indent=2))
    elif args.action == "validate":
        result = validate_domain(args.domain_id)
        print(f"Domains: {'PASS' if result['passed'] else 'FAIL'}")
        for check in result['checks']:
            print(f"- [{'x' if check['passed'] else ' '}] {check['id']} missing={','.join(check['missing']) or '-'}")
        if not result['passed']:
            raise SystemExit(1)
    elif args.action == "scaffold":
        out = scaffold_domain(args.domain_id, args.label, force=args.force)
        print(f"Domain scaffolded: {out}")
    elif args.action == "benchmark":
        result = benchmark_domain(args.domain_id)
        print(f"Domain benchmark {args.domain_id}: {'PASS' if result['passed'] else 'FAIL'} detected={result['detected']} score={result['score']:.3f} confidence={result['confidence']}")
        print(result['explanation'])
        if not result['passed']:
            raise SystemExit(1)
    elif args.action == "update":
        out = update_domain(args.domain_id, {args.field: args.values})
        print(f"Domain updated: {out}")
    elif args.action == "export":
        out = export_domain(args.domain_id, Path(args.out_dir))
        print(f"Domain exported: {out}")
    elif args.action == "import":
        out = import_domain(Path(args.path), force=args.force)
        print(f"Domain imported: {out}")

def cmd_eval(args):
    eval_root = Path(args.root) / "eval-runs"
    if args.benchmark:
        cases = V12_SAMPLE_CASES if args.samples == "asset-legaliq-crm" else None
        result = run_benchmark(eval_root, cases=cases, export_docx_enabled=not args.no_docx,
                               llm_provider=_resolve_llm_provider(args.llm), llm_model=args.model or DEFAULT_LLM_MODEL)
        print(f"Benchmark {result.name}: {'PASS' if result.passed else 'FAIL'} score={result.score:.2%}")
        print(f"Report: {result.report_path}")
        print(f"Results: {result.results_path}")
        for case in result.case_results:
            print(f"- {'PASS' if case.passed else 'FAIL'} {case.name}: score={float(case.details['score']):.2%} gates={float(case.details['gate_pass_rate']):.2%} trace_edges={case.details['trace_edges']}")
    else:
        result = run_eval(eval_root)
        print(f"Eval {result.name}: {'PASS' if result.passed else 'FAIL'}")
        for k, v in result.details.items():
            print(f"- {k}: {v}")


def build_parser():
    parser = argparse.ArgumentParser(prog="pmo", description="PMO Studio v2.1")
    parser.add_argument("--root", default=str(DEFAULT_ROOT))
    sub = parser.add_subparsers(required=True)
    init = sub.add_parser("init")
    init.add_argument("slug")
    init.add_argument("--customer", default="TBD")
    init.add_argument("--brief", default="Tạo hệ thống PMO Studio v2.1 cho tài liệu dự án phần mềm.")
    init.add_argument("--product", action="append", default=["eOffice"])
    init.add_argument("--domain-pack", default="bteco", choices=["bteco", "eoffice", "ky_so", "hse", "pms"], help="Domain intelligence pack for domain-specific content")
    init.add_argument("--source", action="append", default=[])
    init.set_defaults(func=cmd_init)
    gen = sub.add_parser("generate")
    gen.add_argument("slug", nargs="?")
    gen.add_argument("persona", choices=["po", "pm", "ba", "ic", "all"])
    gen.add_argument("--from-sources", action="store_true", help="Generate BA artifacts from redacted sources with optional LLM fallback")
    gen.add_argument("--llm", choices=["auto", "noop", "9router"], default=DEFAULT_LLM_PROVIDER, help="Default auto uses 9router/Tier2 when API key is available, otherwise noop fallback")
    gen.add_argument("--model", default=DEFAULT_LLM_MODEL)
    gen.add_argument("--refine", action=argparse.BooleanOptionalAction, default=True, help="Run Gate A/B feedback refinement loop for generated Markdown artifacts (default: on)")
    gen.add_argument("--max-refine", type=int, default=DEFAULT_MAX_REFINE, help="Maximum refinement attempts per Markdown artifact")
    gen.set_defaults(func=cmd_generate)
    gate = sub.add_parser("gate")
    gate.add_argument("slug", nargs="?")
    gate.add_argument("stage")
    gate.add_argument("artifact")
    gate.add_argument("--layer", choices=["A", "B", "C"], default="A")
    gate.add_argument("--llm", choices=["auto", "noop", "9router"], default=DEFAULT_LLM_PROVIDER)
    gate.add_argument("--model", default=DEFAULT_LLM_MODEL)
    gate.set_defaults(func=cmd_gate)
    trace = sub.add_parser("trace")
    trace.add_argument("slug", nargs="?")
    trace.add_argument("--validate", action="store_true")
    trace.set_defaults(func=cmd_trace)
    detect = sub.add_parser("detect-domain")
    detect.add_argument("slug", nargs="?")
    detect.set_defaults(func=cmd_detect_domain)
    man = sub.add_parser("manifest")
    man.add_argument("slug", nargs="?")
    man.set_defaults(func=cmd_manifest)
    tmpl = sub.add_parser("templates")
    tmpl.add_argument("action", choices=["list", "validate"])
    tmpl.set_defaults(func=cmd_templates)
    runp = sub.add_parser("run-project", help="One-command project pipeline")
    runp.add_argument("slug")
    runp.add_argument("--source", required=True)
    runp.add_argument("--customer", default="TBD")
    runp.add_argument("--product", default="PMO Studio Project")
    runp.add_argument("--brief", default="Generate a client-ready PMO documentation pack from source.")
    runp.add_argument("--domain-pack", default="generic")
    runp.add_argument("--profile", default="customer")
    runp.add_argument("--llm", choices=["auto", "noop", "9router"], default="noop")
    runp.add_argument("--model", default=DEFAULT_LLM_MODEL)
    runp.add_argument("--refine", action=argparse.BooleanOptionalAction, default=False)
    runp.add_argument("--max-refine", type=int, default=0)
    runp.add_argument("--signoff-final", action="store_true")
    runp.add_argument("--by", default="Snail")
    runp.add_argument("--force", action="store_true")
    runp.set_defaults(func=cmd_run_project)
    idx = sub.add_parser("index")
    idx.add_argument("slug", nargs="?")
    idx.set_defaults(func=cmd_index)
    so = sub.add_parser("signoff")
    so.add_argument("slug", nargs="?")
    so.add_argument("role", choices=["PO", "PM", "BA", "IC", "Quotation", "Final"])
    so.add_argument("status", choices=["approved", "rejected", "pending"])
    so.add_argument("--by", default="Snail")
    so.add_argument("--note", default="")
    so.set_defaults(func=cmd_signoff)
    exp = sub.add_parser("export")
    exp.add_argument("slug", nargs="?")
    exp.add_argument("--format", choices=["html", "docx", "zip", "pdf", "pdf-html", "all"], default="html")
    exp.add_argument("--profile", default="client-ready")
    exp.add_argument("--include-redacted-sources", action="store_true", help="Include redacted sources in ZIP bundle; originals are never included")
    exp.add_argument("--force", action="store_true", help="Allow explicit re-export after final sign-off lock")
    exp.set_defaults(func=cmd_export)
    baseline = sub.add_parser("baseline")
    baseline.add_argument("slug", nargs="?")
    baseline.add_argument("version")
    baseline.set_defaults(func=cmd_baseline)
    diff = sub.add_parser("diff")
    diff.add_argument("slug", nargs="?")
    diff.add_argument("version")
    diff.set_defaults(func=cmd_diff)
    cr = sub.add_parser("cr")
    cr.add_argument("slug", nargs="?")
    cr.add_argument("baseline")
    cr.add_argument("--title", required=True)
    cr.add_argument("--description", required=True)
    cr.add_argument("--requested-by", default="Snail")
    cr.set_defaults(func=cmd_cr)
    sc = sub.add_parser("scaffold")
    sc.set_defaults(func=cmd_scaffold)
    rg = sub.add_parser("run-gates")
    rg.add_argument("slug", nargs="?")
    rg.add_argument("--include-c", action=argparse.BooleanOptionalAction, default=True, help="Run Gate C/business-readiness checks by default")
    rg.add_argument("--llm", choices=["auto", "noop", "9router"], default=DEFAULT_LLM_PROVIDER)
    rg.add_argument("--model", default=DEFAULT_LLM_MODEL)
    rg.add_argument("--gate-cache", default=None, help="Cache directory for LLM Gate B/C reviews")
    rg.add_argument("--gate-timeout", type=int, default=DEFAULT_GATE_TIMEOUT, help="Per-review LLM timeout in seconds")
    rg.add_argument("--gate-fallback", action=argparse.BooleanOptionalAction, default=True, help="Return failing gate checks instead of raising on LLM errors")
    rg.set_defaults(func=cmd_run_gates)
    ls = sub.add_parser("list")
    ls.add_argument("--refresh", action="store_true")
    ls.add_argument("--limit", type=int, default=20)
    ls.add_argument("--include-archived", action="store_true")
    ls.set_defaults(func=cmd_list)
    recent = sub.add_parser("recent")
    recent.set_defaults(func=cmd_recent)
    summ = sub.add_parser("summary")
    summ.add_argument("slug", nargs="?")
    summ.set_defaults(func=cmd_summary)
    sync = sub.add_parser("sync-lifecycle")
    sync.add_argument("slug", nargs="?")
    sync.set_defaults(func=cmd_sync_lifecycle)
    setlife = sub.add_parser("set-lifecycle")
    setlife.add_argument("slug", nargs="?")
    setlife.add_argument("state", choices=["INITIATED", "GENERATED", "GATED", "EXPORTED", "BASELINED", "ARCHIVED"])
    setlife.set_defaults(func=cmd_set_lifecycle)
    arch = sub.add_parser("archive")
    arch.add_argument("slug", nargs="?")
    arch.add_argument("--reason", default="")
    arch.add_argument("--move", action="store_true", help="Move project folder under _archived/")
    arch.add_argument("--yes", action="store_true", help="Required confirmation flag")
    arch.set_defaults(func=cmd_archive)
    clone = sub.add_parser("clone")
    clone.add_argument("slug", nargs="?")
    clone.add_argument("new_slug")
    clone.add_argument("--customer", default=None)
    clone.set_defaults(func=cmd_clone)
    doc = sub.add_parser("doctor")
    doc.add_argument("slug", nargs="?")
    doc.set_defaults(func=cmd_doctor)
    demo = sub.add_parser("demo", help="Run a bundled end-to-end demo")
    demo.add_argument("name", choices=["asset-management"])
    demo.add_argument("--slug", default="asset-management-demo")
    demo.add_argument("--customer", default="Demo Asset Customer")
    demo.add_argument("--force", action="store_true", help="Overwrite existing demo project")
    demo.add_argument("--llm", choices=["auto", "noop", "9router"], default="noop")
    demo.add_argument("--model", default=DEFAULT_LLM_MODEL)
    demo.set_defaults(func=cmd_demo)
    web = sub.add_parser("web", help="Run local PMO Studio Web UI")
    web.add_argument("--host", default="127.0.0.1")
    web.add_argument("--port", type=int, default=8765)
    web.set_defaults(func=cmd_web)
    tg = sub.add_parser("telegram", help="Prepare Telegram delivery manifests without sending tokens/messages")
    tg_sub = tg.add_subparsers(dest="action", required=True)
    ting = tg_sub.add_parser("ingest")
    ting.add_argument("--chat-id", required=True); ting.add_argument("--message-id", default=None); ting.add_argument("--source", default=None); ting.add_argument("--text", default=None); ting.add_argument("--slug", default=None); ting.add_argument("--customer", default=None); ting.add_argument("--product", default=None); ting.set_defaults(func=cmd_telegram)
    trun = tg_sub.add_parser("run-session")
    trun.add_argument("--chat-id", required=True); trun.add_argument("--llm", choices=["auto", "noop", "9router"], default="noop"); trun.add_argument("--force", action="store_true"); trun.set_defaults(func=cmd_telegram)
    tses = tg_sub.add_parser("session")
    tses.add_argument("--chat-id", required=True); tses.set_defaults(func=cmd_telegram)
    tprep = tg_sub.add_parser("prepare")
    tprep.add_argument("slug"); tprep.add_argument("--source", required=True); tprep.add_argument("--customer", default="TBD"); tprep.add_argument("--product", default="PMO Studio Project")
    tprep.add_argument("--brief", default="Generate a client-ready PMO documentation pack from Telegram inbound source.")
    tprep.add_argument("--domain-pack", default="generic"); tprep.add_argument("--chat-id", default=None); tprep.add_argument("--llm", choices=["auto", "noop", "9router"], default="noop"); tprep.add_argument("--model", default=DEFAULT_LLM_MODEL); tprep.add_argument("--by", default="Telegram Workflow"); tprep.add_argument("--force", action="store_true")
    tprep.set_defaults(func=cmd_telegram)
    tman = tg_sub.add_parser("manifest")
    tman.add_argument("slug"); tman.add_argument("--chat-id", default=None); tman.set_defaults(func=cmd_telegram)
    dom = sub.add_parser("domains", help="Manage YAML domain packs")
    dom_sub = dom.add_subparsers(dest="action", required=True)
    dlist = dom_sub.add_parser("list"); dlist.set_defaults(func=cmd_domains)
    dins = dom_sub.add_parser("inspect"); dins.add_argument("domain_id"); dins.set_defaults(func=cmd_domains)
    dval = dom_sub.add_parser("validate"); dval.add_argument("domain_id", nargs="?"); dval.set_defaults(func=cmd_domains)
    dsc = dom_sub.add_parser("scaffold"); dsc.add_argument("domain_id"); dsc.add_argument("--label", required=True); dsc.add_argument("--force", action="store_true"); dsc.set_defaults(func=cmd_domains)
    dben = dom_sub.add_parser("benchmark"); dben.add_argument("domain_id"); dben.set_defaults(func=cmd_domains)
    dup = dom_sub.add_parser("update"); dup.add_argument("domain_id"); dup.add_argument("field"); dup.add_argument("values"); dup.set_defaults(func=cmd_domains)
    dexp = dom_sub.add_parser("export"); dexp.add_argument("domain_id"); dexp.add_argument("--out-dir", default="."); dexp.set_defaults(func=cmd_domains)
    dimp = dom_sub.add_parser("import"); dimp.add_argument("path"); dimp.add_argument("--force", action="store_true"); dimp.set_defaults(func=cmd_domains)
    ev = sub.add_parser("eval")
    ev.add_argument("--benchmark", action="store_true", help="Run multi-project benchmark suite")
    ev.add_argument("--samples", choices=["default", "asset-legaliq-crm"], default="default")
    ev.add_argument("--no-docx", action="store_true", help="Skip DOCX export during benchmark")
    ev.add_argument("--llm", choices=["auto", "noop", "9router"], default=DEFAULT_LLM_PROVIDER)
    ev.add_argument("--model", default=DEFAULT_LLM_MODEL)
    ev.set_defaults(func=cmd_eval)
    return parser


def main(argv=None):
    parser = build_parser()
    args = parser.parse_args(argv)
    args.func(args)


if __name__ == "__main__":
    main()
